spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/webserver_db
    username: jrdevangel
    password: iMacniaco

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000