spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webserver_db
    username: jrdevangel
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    sql:
      init:
        mode: never